language: node_js
dist: xenial
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
install:
  - npm install
  - DEPLOY_ENV=GH_PAGES npm run generate
notifications:
  email: false
script:
  - echo "Skipping tests"
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  repo: Bitti09/vue-wf
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master
