language: node_js
dist: xenial
node_js:
    - "node"
install:
    - npm install -g @vue/cli
    - npm install
script:
    - npm run build
cache: npm
branches:
  only:
  - master
  - /^greenkeeper/.*$/
notifications:
    email: false
deploy:
    provider: pages
    skip-cleanup: true
    local-dir: dist
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    repo: Bitti09/vue-wf
    keep-history: true
    target-branch: gh-pages
    on:
        branch: master