query Alerts($Expiry_gte: Int, $platform: String) {
  Alerts(where: { Expiry_gte: $Expiry_gte, platform: $platform }) {
    alertid
    Expiry
    MissionType
    MissionFaction
    MissionLocation
    MissionRewardItem
    MissionRewardCredits
    MissionRewardImg
    MissionMinEnemyLvl
    MissionMaxEnemyLevel
    MissionNightmareMode
    MissionAchwingRequired
  }
}
